using System;
// מחלקת בדיקה רפואית
public class PhysicalExam
{
    public int UpdateCode { get; set; }
    public bool ApearsWell { get; set; }
    public string ApearsWellT { get; set; }
    public bool PupilsEqual { get; set; }
    public string PupilsEqualT { get; set; }
    public bool TmNormal { get; set; }
    public string TmNormalT { get; set; }
    public bool Oropharynx { get; set; }
    public string OropharynxT { get; set; }
    public bool Atraumatic { get; set; }
    public string AtraumaticT { get; set; }
    public bool HeentMucosa { get; set; }
    public string HeentMucosaT { get; set; }
    public bool Supple { get; set; }
    public string SuppleT { get; set; }
    public bool thyromegaly { get; set; }
    public string thyromegalyT { get; set; }
    public bool HeartsoundsRegular { get; set; }
    public string HeartsoundsRegularT { get; set; }
    public bool Murmur { get; set; }
    public string MurmurT { get; set; }
    public bool GoodAir { get; set; }
    public string GoodAirT { get; set; }
    public bool ClearToAuscultation { get; set; }
    public string ClearToAuscultationT { get; set; }
    public bool SymmetricalBreast { get; set; }
    public string SymmetricalBreastT { get; set; }
    public bool Palpable { get; set; }
    public string PalpableT { get; set; }
    public bool SkinChanges { get; set; }
    public string SkinChangesT { get; set; }
    public bool Nipple { get; set; }
    public string NippleT { get; set; }
    public bool Axillary { get; set; }
    public string AxillaryT { get; set; }
    public bool Soft { get; set; }
    public string SoftT { get; set; }
    public bool Tender { get; set; }
    public string TenderT { get; set; }
    public string ABDdescription { get; set; }
    public bool BowelSounds { get; set; }
    public string BowelSoundsT { get; set; }
    public bool RenalArtery { get; set; }
    public string RenalArteryT { get; set; }
    public bool Masses { get; set; }
    public string MassesT { get; set; }
    public bool Organomegaly { get; set; }
    public string OrganomegalyT { get; set; }
    public bool SkinAbnormalities { get; set; }
    public string SkinAbnormalitiesT { get; set; }
    public bool SignificantScoliosis { get; set; }
    public string SignificantScoliosisT { get; set; }
    public bool Kyphosis { get; set; }
    public string KyphosisT { get; set; }
    public bool Edema { get; set; }
    public string EdemaT { get; set; }
    public bool EXTRash { get; set; }
    public string EXTRashT { get; set; }
    public bool Varicosities { get; set; }
    public string VaricositiesT { get; set; }
    public bool Pppx4 { get; set; }
    public string Pppx4T { get; set; }
    public bool PedalEdema { get; set; }
    public string PedalEdemaT { get; set; }
    public bool Toes { get; set; }
    public string ToesT { get; set; }
    public bool Pattelar { get; set; }
    public string PattelarT { get; set; }
    public bool Gait { get; set; }
    public string GaitT { get; set; }
    public bool Speech { get; set; }
    public string SpeechT { get; set; }
    public bool Female { get; set; }
    public string FemaleT { get; set; }
    public int PelvicMucosa { get; set; }
    public int Kegels { get; set; }
    public string Cervix { get; set; }
    public bool VaginalWalls { get; set; }
    public string VaginalWallsT { get; set; }
    public bool Pap { get; set; }
    public string PapT { get; set; }

}
